[versions]
# ── Core Build Tools ─────────────────────────────────────
kotlin = "1.9.22"                    # Stable Kotlin version
agp = "8.2.2"                        # Stable Android Gradle Plugin
hilt = "2.50"                        # Dagger Hilt DI library
googleServices = "4.4.0"             # Google Services plugin

# ── Jetpack Compose ──────────────────────────────────────
composeBom = "2024.02.00"           # Stable Compose BOM
composeUi = "1.6.1"                 # Compose UI base version
material3 = "1.2.0"                 # Material Design 3 components
activityCompose = "1.8.2"           # Compose-compatible Activity
composeCompiler = "1.5.8"           # Compose Compiler version

# ── AndroidX & Lifecycle ─────────────────────────────────
coreKtx = "1.12.0"
lifecycle = "2.7.0"
navigation = "2.7.6"
runtimeLiveData = "1.5.4"

# ── Room ORM ─────────────────────────────────────────────
room = "2.6.1"

# ── Kotlin Coroutines ────────────────────────────────────
coroutines = "1.7.3"

# ── Firebase ─────────────────────────────────────────────
firebaseAuthKtx = "22.3.1"

# ── Testing ──────────────────────────────────────────────
junit = "4.13.2"

[libraries]
# ── Jetpack Compose Core ─────────────────────────────────
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "composeUi" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUi" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }

# ── Compose Navigation & Activity ────────────────────────
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

# ── AndroidX Lifecycle / ViewModel ───────────────────────
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

# ── LiveData in Compose ──────────────────────────────────
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLiveData" }

# ── Room ORM Database ────────────────────────────────────
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# ── Kotlin Coroutines ────────────────────────────────────
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

# ── Firebase ─────────────────────────────────────────────
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebaseAuthKtx" }

# ── Hilt Dependency Injection ────────────────────────────
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

# ── Testing ──────────────────────────────────────────────
junit = { module = "junit:junit", version.ref = "junit" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeUi" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeUi" }

[plugins]
# ── Gradle Plugin Aliases ────────────────────────────────
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }

# ── Kotlin Compose Compiler Plugin ─
kotlin-plugin-compose = { id = "org.jetbrains.compose", version.ref = "composeCompiler" }
