[versions]
# --------------------------------------------------
# Core Build Tool Versions
# --------------------------------------------------
kotlin = "2.1.10"
agp = "8.6.1"

# --------------------------------------------------
# Jetpack Compose Versions (BOM & Libraries)
# --------------------------------------------------
composeBom = "2025.07.00"
composeUi = "1.8.3"
material3 = "1.3.2"                 # Stable Material3 release
activityCompose = "1.10.1"

# --------------------------------------------------
# Jetpack and AndroidX Libraries
# --------------------------------------------------
lifecycle = "2.9.2"
navigation = "2.9.2"
room = "2.7.2"
coreKtx = "1.16.0"
runtimeLiveData = "1.8.3"

# --------------------------------------------------
# Kotlin Coroutines
# --------------------------------------------------
coroutines = "1.8.1"

# --------------------------------------------------
# Testing Libraries
# --------------------------------------------------
junit = "4.13.2"

[libraries]
# --------------------------------------------------
# Jetpack Compose BOM (Version Management)
# --------------------------------------------------
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }

# --------------------------------------------------
# Core Compose Libraries
# --------------------------------------------------
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "composeUi" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUi" }

# --------------------------------------------------
# Compose Testing Libraries
# --------------------------------------------------
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeUi" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeUi" }

# --------------------------------------------------
# Activity Integration for Compose
# --------------------------------------------------
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

# --------------------------------------------------
# Jetpack Navigation Compose Integration
# --------------------------------------------------
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

# --------------------------------------------------
# Lifecycle and ViewModel Libraries
# --------------------------------------------------
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

# --------------------------------------------------
# LiveData Support in Compose
# --------------------------------------------------
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLiveData" }

# --------------------------------------------------
# Room Database Libraries
# --------------------------------------------------
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# --------------------------------------------------
# Core AndroidX Extensions
# --------------------------------------------------
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }

# --------------------------------------------------
# Kotlin Coroutines Libraries
# --------------------------------------------------
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

# --------------------------------------------------
# JUnit Testing Library
# --------------------------------------------------
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
# --------------------------------------------------
# Android Gradle Plugin
# --------------------------------------------------
android-application = { id = "com.android.application", version.ref = "agp" }

# --------------------------------------------------
# Kotlin Android and Annotation Processing Plugins
# --------------------------------------------------
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
