package com.example.fitnesstrackerapp.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Diet
 *
 * Entity class for tracking diet/nutrition intake in the app.
 * Represents each food item logged by the user.
 * Stored in the Room database table named "diets".
 */
@Entity(tableName = "diets")
data class Diet(

    /**
     * Primary key for each diet entry.
     * Auto-generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    /**
     * Name or description of the food consumed.
     * Example: "Grilled Chicken Salad"
     */
    val food: String,

    /**
     * Number of calories in the food item (in kcal).
     * Example: 350
     */
    val calories: Int,

    /**
     * Timestamp when the diet entry was logged.
     * Stored as Unix time in milliseconds.
     * Default value: current system time.
     */
    val date: Long = System.currentTimeMillis()
)
