package com.example.fitnesstrackerapp.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Diet
 *
 * Represents a single diet or nutrition entry in the app.
 * Each record contains a food description, its calorie count, and the date it was logged.
 * Stored in the Room database in a table named "diets".
 */
@Entity(tableName = "diets")
data class Diet(

    /**
     * Primary key ID for the diet entry.
     * Automatically generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    /**
     * The name or description of the food item consumed.
     * Example: "Grilled Chicken Salad"
     * Should not be blank in actual usage (validate at UI level).
     */
    val food: String,

    /**
     * The number of calories in the food item (in kilocalories).
     * Must be a positive integer (enforce in ViewModel/UI).
     * Example: 350
     */
    val calories: Int,

    /**
     * Timestamp of when this food item was consumed or logged.
     * Stored as Unix time in milliseconds.
     * Defaults to current system time.
     */
    val date: Long = System.currentTimeMillis()
)
