package com.example.fitnesstrackerapp.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Workout
 *
 * Entity representing a workout log in the Room database.
 * Each record includes metadata about a physical activity like running, cycling, etc.
 */
@Entity(tableName = "workouts")
data class Workout(

    /**
     * Unique ID for this workout (auto-generated by Room).
     */
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    /**
     * Type or name of the workout (e.g., "Running", "Swimming", "Yoga").
     * Should be a non-blank string (enforce via UI/validation).
     */
    val type: String,

    /**
     * Duration of the workout in minutes.
     * Must be a positive number (validate in ViewModel or UI).
     */
    val duration: Int,

    /**
     * Distance covered during the workout (in kilometers).
     * Can be 0.0 for workouts like yoga or strength training.
     */
    val distance: Double,

    /**
     * Estimated calories burned during the workout.
     * Should be ≥ 0.
     */
    val calories: Int,

    /**
     * Optional user notes about the workout.
     * Default is an empty string.
     * Example: "Felt strong", "Morning jog", etc.
     */
    val notes: String = "",

    /**
     * Timestamp when the workout was logged, in Unix milliseconds.
     * Defaults to the current system time.
     */
    val date: Long = System.currentTimeMillis()
)
